name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v3
        with:
          issue_message: |
            "こんにちは！プルリクエストを作成していただき、ありがとうございます。
            このリポジトリへの初めての貢献を歓迎します！"
          pr_message: |
            "こんにちは！プルリクエストを作成していただき、ありがとうございます。
            このリポジトリへの初めての貢献を歓迎します！"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
